f1 = open("transf.txt",'r')
# f2 = open("StoreTraffic.txt",'r')
x1 = f1.read()
# x2 = f2.read()
y1 = x1.replace(" ",'')
y1 = y1.replace("	","")
# y2 = x2.replace(" ",'')
# y2 = y2.replace("	","")
f3 = open('out1.txt','w')
f3.write(y1)
f3.close()
# f4 = open('out2.txt','w')
# f4.write(y2)
# f4.close()